version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Npgsql.EntityFrameworkCore.PostgreSQL
    versions:
    - 5.0.2
    - 5.0.5
  - dependency-name: Google.Apis.YouTube.v3
    versions:
    - 1.49.0.2217
    - 1.49.0.2225
    - 1.50.0.2228
    - 1.50.0.2232
    - 1.50.0.2238
    - 1.51.0.2238
    - 1.51.0.2287
    - 1.51.0.2288
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Mvc.Testing
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: NSwag.MSBuild
    versions:
    - 13.10.1
    - 13.10.2
    - 13.10.3
    - 13.10.5
    - 13.10.6
    - 13.10.7
    - 13.10.8
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: nunit
    versions:
    - 3.13.0
    - 3.13.1
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
